#!/usr/bin/env python3
"""
cti_taxonomy_loader.py

Loads the OFFICIAL MITRE ATT&CK dataset (single STIX bundle):

    app/cti_taxonomy/enterprise_attack.json

Provides high-performance lookup tables for Stage 2:

    • attack-patterns (TTPs)
    • malware
    • intrusion-sets (groups)
    • tools
    • relationships
    • name_index (normalized name → object)
    • attack_id_index (T1048 → TTP object)

This replaces the old loader that assumed 3 separate JSON files.
"""

import json, re
import threading
from functools import lru_cache
from pathlib import Path

from plugins.mcp.app.utilities.nlp_model import get_nlp

# Stage 1 fans out over a thread pool and every worker needs both tables.
# lru_cache alone is not single-flight, so racing workers would each pay the
# full build; the lock makes the first caller the only one that computes.
_TAXONOMY_LOCK = threading.Lock()
_PATTERNS_LOCK = threading.Lock()

# ======================================================================
#  Load the unified MITRE ATT&CK bundle
# ======================================================================

def load_mitre_bundle():
    """
    Loads the official enterprise_attack.json file generated by
    install_mitre_taxonomy.py
    """
    base = Path(__file__).resolve().parent / "cti_taxonomy"
    path = base / "enterprise_attack.json"

    if not path.exists():
        raise FileNotFoundError(
            f"MITRE dataset not found at {path}\n"
            f"Run: python3 utilities/install_mitre_taxonomy.py"
        )
    raw = path.read_text(encoding="utf-8")
    if not raw.strip().startswith("{"):
        raise ValueError(f"[MITRE] Unexpected file format at {path}")
    return json.loads(path.read_text(encoding="utf-8"))


# ======================================================================
#  Parse and index MITRE objects
# ======================================================================

@lru_cache(maxsize=1)
def _load_mitre_taxonomy():
    """
    Extracts all relevant MITRE STIX objects and builds fast lookup tables.

    Returns dict with:
        attack_patterns
        malware
        groups
        tools
        relationships
        name_index
        attack_id_index
    """

    try:
        bundle = load_mitre_bundle()
        if "objects" not in bundle:
            raise ValueError("Invalid MITRE bundle — missing 'objects' field")
    except FileNotFoundError as e:
        raise RuntimeError(f"[MITRE] Cannot load ATT&CK bundle: {e}")

    objects = bundle.get("objects", [])

    attack_patterns = {}
    malware = {}
    groups = {}
    tools = {}
    relationships = []
    relationships_by_id = {}


    name_index = {}        # name → (type, id, obj)
    attack_id_index = {}   # T1048 → attack-pattern obj
    matrix_tactic_refs = []
    tactic_shortnames = {}   # x-mitre-tactic id → shortname
    print("[DEBUG] Total MITRE objects loaded:", len(objects))
    for obj in objects:
        obj_type = obj.get("type")
        obj_id = obj.get("id", "")
        name = obj.get("name", "").strip()

        # The matrix states the kill-chain sequence that the tactic objects
        # themselves do not carry.
        if obj_type == "x-mitre-matrix":
            matrix_tactic_refs = obj.get("tactic_refs", []) or []
        elif obj_type == "x-mitre-tactic":
            tactic_shortnames[obj_id] = obj.get("x_mitre_shortname", "")

        # ------------------------------
        # ATTACK PATTERNS (TTPs)
        # ------------------------------
        if obj_type == "attack-pattern":
            attack_patterns[obj_id] = obj

            # external_references → MITRE technique IDs
            for ref in obj.get("external_references", []):
                if ref.get("source_name") in ("mitre-attack", "mitre-mobile-attack"):
                    tid = ref.get("external_id")
                    if tid:
                        attack_id_index[tid.upper().strip()] = obj
                        attack_id_index[tid.replace("(", "").replace(")", "").upper()] = obj
                        attack_id_index[tid.split("/")[0].upper()] = obj

            if name:
                base = name.lower().strip()

                # Exact
                name_index[f"{obj_type}:{base}"] = (obj_type, obj_id, obj)

                # Token-normalized fallback
                norm = re.sub(r"[^a-z0-9]+", " ", base).strip()
                name_index[f"{obj_type}:{norm}"] = (obj_type, obj_id, obj)

            # print("[DEBUG] Loaded attack-pattern:", name)
        # ------------------------------
        # MALWARE
        # ------------------------------
        elif obj_type == "malware":
            malware[obj_id] = obj
            if name:
                base = name.lower().strip()
                name_index[f"malware:{base}"] = ("malware", obj_id, obj)
                norm = re.sub(r"[^a-z0-9]+", " ", base).strip()
                name_index[f"malware:{norm}"] = ("malware", obj_id, obj)

            # print("[DEBUG] Loaded malware:", name)
        # ------------------------------
        # INTRUSION SETS (GROUPS)
        # ------------------------------
        elif obj_type == "intrusion-set":
            groups[obj_id] = obj
            if name:
                base = name.lower().strip()
                name_index[f"intrusion-set:{base}"] = ("intrusion-set", obj_id, obj)
                norm = re.sub(r"[^a-z0-9]+", " ", base).strip()
                name_index[f"intrusion-set:{norm}"] = ("intrusion-set", obj_id, obj)

            # print("[DEBUG] Loaded intrusion-set:", name)
        # ------------------------------
        # TOOLS
        # ------------------------------
        elif obj_type == "tool":
            tools[obj_id] = obj
            if name:
                base = name.lower().strip()
                name_index[f"tool:{base}"] = ("tool", obj_id, obj)
                norm = re.sub(r"[^a-z0-9]+", " ", base).strip()
                name_index[f"tool:{norm}"] = ("tool", obj_id, obj)

            # print("[DEBUG] Loaded tool:", name)
        # ------------------------------
        # RELATIONSHIPS
        # ------------------------------
        elif obj_type == "relationship":
            relationships.append(obj)
            rel_id = obj.get("id")
            relationships_by_id[rel_id] = {
                "id": rel_id,
                "type": obj.get("relationship_type"),
                "source": obj.get("source_ref"),
                "target": obj.get("target_ref")
            }


    # ---------------------------------------------------------
    # DEBUG: Verify indexing worked
    # ---------------------------------------------------------
    print("[DEBUG][MITRE] attack_patterns loaded:", len(attack_patterns))
    print("[DEBUG][MITRE] malware loaded:", len(malware))
    print("[DEBUG][MITRE] groups loaded:", len(groups))
    print("[DEBUG][MITRE] tools loaded:", len(tools))
    print("[DEBUG][MITRE] relationships loaded:", len(relationships))
    print("[DEBUG][MITRE] name_index entries:", len(name_index))
    print("[DEBUG][MITRE] attack_id_index entries:", len(attack_id_index))

    kill_chain_order = tuple(
        tactic_shortnames[ref]
        for ref in matrix_tactic_refs
        if tactic_shortnames.get(ref)
    )
    print("[DEBUG][MITRE] kill_chain_order:", len(kill_chain_order))

    return {
        "attack_patterns": attack_patterns,
        "malware": malware,
        "groups": groups,
        "tools": tools,
        "relationships": relationships,
        "relationships_by_id": relationships_by_id,
        "name_index": name_index,
        "attack_id_index": attack_id_index,
        "kill_chain_order": kill_chain_order,
    }


def load_mitre_taxonomy():
    """Return the shared MITRE taxonomy. Built once, read-only thereafter."""
    with _TAXONOMY_LOCK:
        return _load_mitre_taxonomy()


# ======================================================================
#  Convenience APIs
# ======================================================================

def lookup_name(name: str, taxonomy: dict):
    """
    Look up any MITRE object by canonical name.
    Returns (type, id, stix_object) or None.
    """
    if not name:
        return None
    norm = re.sub(r"[^a-z0-9]+", " ", name.lower()).strip()
    for prefix in ("attack-pattern", "malware", "tool", "intrusion-set"):
        key = f"{prefix}:{norm}"
        if key in taxonomy["name_index"]:
            return taxonomy["name_index"][key]
    return None


def lookup_attack_id(tid: str, taxonomy: dict):
    """
    Look up MITRE attack-pattern by technique ID, e.g., "T1048".
    """
    if not tid:
        return None
    return taxonomy["attack_id_index"].get(tid.upper().strip())


@lru_cache(maxsize=1)
def _build_normalized_attack_patterns():
    """
    Unified MITRE technique index for Stage-1 and Stage-2.

    Output format:
    {
        "id": "T1059",
        "name": "Command and Scripting Interpreter",
        "description": "...",
        "tokens": {...},             # name tokens
        "desc_tokens": {...},        # description tokens
        "kill_chain": [...],
        "platforms": [...],
        "vector": get_nlp()(description).vector,
    }

    Returns: (techniques_list, lookup_by_id_dict)
    """
    bundle = load_mitre_bundle()
    techniques = []
    by_id = {}

    for obj in bundle.get("objects", []):
        if obj.get("type") != "attack-pattern":
            continue

        # External MITRE technique ID
        tid = None
        for ref in obj.get("external_references", []):
            if ref.get("source_name") == "mitre-attack":
                tid = ref.get("external_id")
                break
        if not tid:
            continue

        name = obj.get("name", "")
        desc = obj.get("description", "") or ""
        tokens = set(re.findall(r"[a-z0-9]+", name.lower()))
        desc_tokens = set(re.findall(r"[a-z0-9]+", desc.lower()))
        kill_chain = [kc.get("phase_name", "").lower() for kc in obj.get("kill_chain_phases", [])]
        platforms = [p.lower() for p in obj.get("x_mitre_platforms", [])]

        entry = {
            "id": tid,
            "name": name,
            "description": desc,
            "tokens": tokens,
            "desc_tokens": desc_tokens,
            "kill_chain": kill_chain,
            "platforms": platforms,
            "vector": get_nlp()(desc).vector.tolist()
        }

        techniques.append(entry)
        by_id[tid] = entry

    return techniques, by_id


def build_normalized_attack_patterns():
    """Return (techniques, by_id). Vectorising 835 descriptions costs ~30s, and
    Stage 1 asks for it once per document, so the result is shared."""
    with _PATTERNS_LOCK:
        return _build_normalized_attack_patterns()