//tealium universal tag - utag.264 ut4.0.202511180232, Copyright 2025 Tealium.com Inc. All Rights Reserved.
window["clarity"]=window["clarity"]||function(){(window["clarity"].q=window["clarity"].q||[]).push(arguments)};try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<41){u.loader=function(o,a,b,c,l,m){utag.DB(o);a=document;if(o.type=="iframe"){m=a.getElementById(o.id);if(m&&m.tagName=="IFRAME"){b=m;}else{b=a.createElement("iframe");}o.attrs=o.attrs||{};utag.ut.merge(o.attrs,{"height":"1","width":"1","style":"display:none"},0);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";}if(o.id){b.id=o.id;}for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=="complete"||this.readyState=="loaded"){this.onreadystatechange=null;o.cb();}};}}if(o.type!="img"&&!m){l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={view:1,link:1};u.initialized=false;u.scriptrequested=false;u.toBoolean=function(val){val=val||"";return val===true||val.toLowerCase()==="true"||val.toLowerCase()==="on";};u.loaderCallback=function(data_layer){utag.DB("send:264:CALLBACK");u.initialized=true;u.callback(data_layer);utag.DB("send:264:CALLBACK:COMPLETE");};u.callback=function(data_layer){if(u.hasConsent(data_layer)){window.clarity("consent");}else{window.clarity("consent",false);}
u.data.events.forEach(function(eventName){u.sendEvent(eventName);});};u.sendEvent=function(eventName){switch(eventName){case'enable_consent':window.clarity('consent');break;case'disable_consent':window.clarity('consent',false);break;default:utag.DB(u.id+": Received unknown event: '"+eventName+"'.");}};u.hasConsent=function(data_layer){if(u.data.ad_storage==="granted"){return true;}
if(utag.gdpr&&u.toBoolean(u.data.tealium_consent)){var consentState=utag.gdpr.getConsentState();if(consentState===1){return true;}
if(consentState===-1||consentState===0){return false;}
if(Array.isArray(consentState)){return utag.gdpr.getSelectedCategories().indexOf("analytics")!==-1;}}
if(data_layer["microsoft_ad_storage_consent"]==="granted"){return true;}
return false;};u.map={};u.extend=[];u.send=function(utag_event,data_layer){if(u.ev[utag_event]||u.ev.all!==undefined){utag.DB("send:264");utag.DB(data_layer);var a,b,c,d,e,f;a=utag_event;b=data_layer;u.data={project_id:"sjbgghj1f5",ad_storage:"granted",tealium_consent:"false",base_url:"https://www.clarity.ms/tag/##project_id##",events:[]};utag.DB("send:264:EXTENSIONS");utag.DB(data_layer);Object.keys(utag.loader.GV(u.map)).forEach(function(mapping_key){if(data_layer[mapping_key]!==undefined&&data_layer[mapping_key]!==""){var destinations=u.map[mapping_key].split(",");destinations.forEach(function(parameter){u.data[parameter]=data_layer[mapping_key];});}else{var event_destinations=mapping_key.split(":");if(event_destinations.length===2&&String(data_layer[event_destinations[0]])===String(event_destinations[1])){if(u.map[mapping_key]){u.data.events=u.data.events.concat(u.map[mapping_key].split(","));}}}});utag.DB("send:264:MAPPINGS");utag.DB(u.data);if(!u.data.project_id){utag.DB(u.id+": Tag not fired: Required attribute Project ID not populated");return;}
u.data.base_url=u.data.base_url.replace("##project_id##",u.data.project_id);if(u.initialized){u.callback(data_layer);}else{if(!u.scriptrequested){u.scriptrequested=true;u.loader({type:"script",src:u.data.base_url,cb:function(){u.loaderCallback(data_layer);},loc:"script",id:"utag_264",attrs:{}});}}
utag.DB("send:264:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("264","trendmicro.nabucms"));}catch(error){utag.DB(error);}
